define 'interface', ->
  (Jasmine, Wrapper)->
    return {} unless Jasmine
    return {} unless Wrapper

    autoGeneratedMethods = ['it', 'iit', 'fit', 'xit']

    for method in autoGeneratedMethods
      if Jasmine.hasOwnProperty(method) and typeof(Jasmine[method]) == 'function'
        this[method] = do (method = method)->
          ->
            Jasmine[method].apply(this,
              Wrapper(arguments...).it())

    @set = (callback)->
      try
        callback.apply(this)
      catch e
        switch e.name
          when 'ReferenceError'
            newCallback = new CallbackWrapper(callback)
            newCallback.apply(this)

    # genarating the following functions:
    # @it = ()->
    #   Jasmine.it.apply(
    #     this,
    #     Wrapper(arguments...).it()
    #   )

    # @iit = ()->
    #   Jasmine.iit.apply(
    #     this,
    #     Wrapper(arguments...).it()
    #   )

    # @fit = ()->
    #   Jasmine.fit.apply(
    #     this,
    #     Wrapper(arguments...).it()
    #   )

    # @xit = ()->
    #   Jasmine.xit.apply(
    #     this,
    #     Wrapper(arguments...).it()
    #   )

    this